### ISSUE TITLE
OutputPath "$.[0]" causes an error during validation

### ISSUE THREAD

**Issue by MoJo2600** [ChristopheBougere/asl-validator#47]
Hello,

When setting the `OutputPath` of a step function to `"$.[0]"` the following error occurs although this is a valid output of a step function.

```
✕ State machine definition is invalid: [ Error: Parse error on line 1:
  $.[0]
  --^
  Expecting 'STAR', 'IDENTIFIER', 'SCRIPT_EXPRESSION', 'INTEGER', 'END', got '['
      at Parser.parseError (/home/mojo/node_modules/jsonpath/generated/parser.js:166:15)
      at Parser.parser.yy.parseError (/home/mojo/node_modules/jsonpath/lib/parser.js:13:17)
      at Parser.parse (/home/mojo/node_modules/jsonpath/generated/parser.js:224:22)
      at JSONPath.parse (/home/mojo/node_modules/jsonpath/lib/index.js:17:22)
      at jp.query.filter.map (/home/mojo/node_modules/asl-validator/src/lib/json-path-errors.js:7:10)
      at Array.map (<anonymous>)
      at module.exports.definition (/home/mojo/node_modules/asl-validator/src/lib/json-path-errors.js:5:4)
      at validator (/home/mojo/node_modules/asl-validator/src/validator.js:33:26)
      at Object.<anonymous> (/home/mojo/node_modules/asl-validator/bin/asl-validator.js:55:18)
      at Module._compile (internal/modules/cjs/loader.js:778:30) ]
``` 
My minimal step function to reproduce this error is:

```
{
	"StartAt": "SampleTask",
	"States": {
		"SampleTask": {
			"Type": "Task",
			"OutputPath": "$.[0]",
			"Resource": {
				"Fn::GetAtt": [
					"account-input",
					"Arn"
				]
			},
			"End": true
		}
	}
}
```
What i don't understand is, that it seems like the schema is just checking if it is string or null. So i don't get why a string with a bracket causes this issue.

Thank you!

**Comment by ChristopheBougere** [comment]
Thanks for reporting @MoJo2600.
This looks like an error from the `jsonpath` package:
```
$ npm install jsonpath
$ node
> const jp = require('jsonpath');
undefined
> jp.parse("$.[0]")
Thrown:
Error: Parse error on line 1:
$.[0]
--^
Expecting 'STAR', 'IDENTIFIER', 'SCRIPT_EXPRESSION', 'INTEGER', 'END', got '['
    at Parser.parseError (/Users/christophe/node_modules/jsonpath/generated/parser.js:166:15)
    at Parser.parser.yy.parseError (/Users/christophe/node_modules/jsonpath/lib/parser.js:13:17)
    at Parser.parse (/Users/christophe/node_modules/jsonpath/generated/parser.js:224:22)
    at JSONPath.parse (/Users/christophe/node_modules/jsonpath/lib/index.js:17:22)
```

Can you confirm this JSON path is supposed to be valid? And if so, couldn't you use `$[0]` instead?

**Comment by MoJo2600** [comment]
Yes, I suspected jsonpath as well. Hm... tried everything like escaping, but to use `$[0]` instead never came to my mind. I will try this! Thank you.

**Comment by ChristopheBougere** [comment]
Closing as it looks fixed, feel free to reopen if it is not @MoJo2600

**Comment by MoJo2600** [comment]
Yes, $[0] works as expected!
